on:
    push:
      branches:
         - master

jobs:
           build:
             runs-on: ubuntu-latest
             steps:
              - name: "log into docker"
                run: docker login
              - name: "building docker image"
                run: docker build -t dockerfile .
